//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeLoan.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class application
    {
        [DataMember]
        public long appId { get; set; }
        [DataMember]
        public long loginid { get; set; }
        [DataMember]
        public string status { get; set; }
    
        public virtual login login { get; set; }
        public virtual document document { get; set; }
        public virtual incomeDetail incomeDetail { get; set; }
        public virtual loan loan { get; set; }
        public virtual loanDetail loanDetail { get; set; }
        public virtual personalDetail personalDetail { get; set; }
        public virtual userBankDetail userBankDetail { get; set; }
    }
}
