//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeLoan.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class document
    {
        [DataMember]
        public long appId { get; set; }
        [DataMember]
        public long aadharNumber { get; set; }
        [DataMember]
        public string PANDoc { get; set; }
        [DataMember]
        public string aadharDoc { get; set; }
        [DataMember]
        public string PAN { get; set; }
        [DataMember]
        public string LOA { get; set; }
        [DataMember]
        public string LOC { get; set; }
        [DataMember]
        public string voterID { get; set; }
        [DataMember]
        public string agreement { get; set; }
    
        public virtual application application { get; set; }
    }
}
