//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeLoan.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class incomeDetail
    {
        [DataMember]
        public long appId { get; set; }
        [DataMember]
        public string propLoc { get; set; }
        [DataMember]
        public string propName { get; set; }
        [DataMember]
        public int propAmount { get; set; }
        [DataMember]
        public string empType { get; set; }
        [DataMember]
        public int retirementAge { get; set; }
        [DataMember]
        public string orgType { get; set; }
        [DataMember]
        public string employer { get; set; }
    
        public virtual application application { get; set; }
    }
}
