//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeLoan.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class loan
    {
        [DataMember]
        public long loanId { get; set; }
        [DataMember]
        public string status { get; set; }
        [DataMember]
        public int amountApproved { get; set; }
        [DataMember]
        public int noOfEmiTotal { get; set; }
        [DataMember]
        public int noOfEmiLeft { get; set; }
        [DataMember]
        public System.DateTime loanDateStart { get; set; }
        [DataMember]
        public string remarks { get; set; }
        [DataMember]
        public long adminId { get; set; }
    
        public virtual application application { get; set; }
        public virtual login login { get; set; }
    }
}
