//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeLoan.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class userBankDetail
    {
        [DataMember]
        public long appId { get; set; }
        [DataMember]
        public long accNo { get; set; }
        [DataMember]
        public string ifsc { get; set; }
    
        public virtual application application { get; set; }
    }
}
